export const mapConstants = {
    SET_CENTER: "SET_CEENTER",
    SET_HOTELS: "SET_HOTELS",
    SET_ROOM_REQUIREMENTS: "SET_ROOM_REQUIREMENTS",
    SET_DATE_RANGE: "SET_DATE_RANGE",
    CLEAR_STATE: "CLEAR_STATE"
}