export const requestConstants = {
    CREATE_REQUEST_REQUEST: "CREATE_REQUEST_REQUEST",
    CREATE_REQUEST_SUCCESS: "CREATE_REQUEST_SUCCESS",
    CREATE_REQUEST_FAILURE: "CREATE_REQUEST_FAILURE",

    GET_ONE_REQUEST_REQUEST: "GET_REQUEST_REQUEST",
    GET_ONE_REQUEST_SUCCESS: "GET_REQUEST_SUCCESS",
    GET_ONE_REQUEST_FAILURE: "GET_REQUEST_FAILURE",

    GET_REQUESTS_REQUEST: "GET_REQUESTS_REQUEST",
    GET_REQUESTS_SUCCESS: "GET_REQUESTS_SUCCESS",
    GET_REQUESTS_FAILURE: "GET_REQUESTS_FAILURE",

    UPDATE_REQUEST_REQUEST: "UPDATE_REQUEST_REQUEST",
    UPDATE_REQUEST_SUCCESS: "UPDATE_REQUEST_SUCCESS",
    UPDATE_REQUEST_FAILURE: "UPDATE_REQUEST_FAILURE",

    DELETE_REQUEST_REQUEST: "DELETE_REQUEST_REQUEST",
    DELETE_REQUEST_SUCCESS: "DELETE_REQUEST_SUCCESS",
    DELETE_REQUEST_FAILURE: "DELETE_REQUEST_FAILURE",

    GET_ONGOING_REQUESTS_REQUEST: "GET_ONGOING_REQUESTS_REQUEST",
    GET_ONGOING_REQUESTS_SUCCESS: "GET_ONGOING_REQUESTS_SUCCESS",
    GET_ONGOING_REQUESTS_FAILURE: "GET_ONGOING_REQUESTS_FAILURE",

    CHANGE_STATUS_REQUEST: "CHANGE_STATUS_REQUEST",
    CHANGE_STATUS_SUCCESS: "CHANGE_STATUS_SUCCESS",
    CHANGE_STATUS_FAILURE: "CHANGE_STATUS_FAILURE",

    BOOK_OFFER_REQUEST: "BOOK_OFFER_REQUEST",
    BOOK_OFFER_SUCCESS: "BOOK_OFFER_SUCCESS",
    BOOK_OFFER_FAILURE: "BOOK_OFFER_FAILURE",

    GET_PREVIOUS_STAYS_REQUEST: "GET_PREVIOUS_STAYS_REQUEST",
    GET_PREVIOUS_STAYS_SUCCESS: "GET_PREVIOUS_STAYS_SUCCESS",
    GET_PREVIOUS_STAYS_FAILURE: "GET_PREVIOUS_STAYS_FAILURE",

    APPROVE_REJECT_UPDATE_REQUEST: "APPROVE_REJECT_UPDATE_REQUEST",
    APPROVE_REJECT_UPDATE_SUCCESS: "APPROVE_REJECT_UPDATE_SUCCESS",
    APPROVE_REJECT_UPDATE_FAILURE: "APPROVE_REJECT_UPDATE_FAILURE",

    GET_REQUEST_UPDATES_REQUEST: "GET_REQUEST_UPDATES_REQUEST",
    GET_REQUEST_UPDATES_SUCCESS: "GET_REQUEST_UPDATES_SUCCESS",
    GET_REQUEST_UPDATES_FAILURE: "GET_REQUEST_UPDATES_FAILURE",

    GET_REJECTED_REQUESTS_REQUEST: "GET_REJECTED_REQUESTS_REQUEST",
    GET_REJECTED_REQUESTS_SUCCESS: "GET_REJECTED_REQUESTS_SUCCESS",
    GET_REJECTED_REQUESTS_FAILURE: "GET_REJECTED_REQUESTS_FAILURE",

    REJECT_REQUEST_REQUEST: "REJECT_REQUEST_REQUEST",
    REJECT_REQUEST_SUCCESS: "REJECT_REQUEST_SUCCESS",
    REJECT_REQUEST_FAILURE: "REJECT_REQUEST_FAILURE",

    GET_REPORTS_REQUEST: "GET_REPORTS_REQUEST",
    GET_REPORTS_SUCCESS: "GET_REPORTS_SUCCESS",
    GET_REPORTS_FAILURE: "GET_REPORTS_FAILURE",

    CLEAR_ERRORS: "CLEAR_ERRORS",

};