export const userConstants = {
  FETCH_USERS_REQUEST: "FETCH_USERS_REQUEST",
  FETCH_USERS_SUCCESS: "FETCH_USERS_SUCCESS",
  FETCH_USERS_FAILURE: "FETCH_USERS_FAILURE",

  FETCH_PERSONAL_INFO_REQUEST: "FETCH_PERSONAL_INFO_REQUEST",
  FETCH_PERSONAL_INFO_SUCCESS: "FETCH_PERSONAL_INFO_SUCCESS",
  FETCH_PERSONAL_INFO_FAILURE: "FETCH_PERSONAL_INFO_FAILURE",

  CREATE_MODERATOR_REQUEST: "CREATE_MODERATOR_REQUEST",
  CREATE_MODERATOR_SUCCESS: "CREATE_MODERATOR_SUCCESS",
  CREATE_MODERATOR_FAILURE: "CREATE_MODERATOR_FAILURE",

  UPDATE_PERSONAL_INFO_REQUEST: "UPDATE_PERSONAL_INFO_REQUEST",
  UPDATE_PERSONAL_INFO_SUCCESS: "UPDATE_PERSONAL_INFO_SUCCESS",
  UPDATE_PERSONAL_INFO_FAILURE: "UPDATE_PERSONAL_INFO_FAILURE",

  BLOCKUNBLOCK_USER_REQUEST: "BLOCKUNBLOCK_USER_REQUEST",
  BLOCKUNBLOCK_USER_SUCCESS: "BLOCKUNBLOCK_USER_SUCCESS",
  BLOCKUNBLOCK_USER_FAILURE: "BLOCKUNBLOCK_USER_FAILURE",

  UPDATE_MODERATOR_REQUEST: "UPDATE_MODERATOR_REQUEST",
  UPDATE_MODERATOR_SUCCESS: "UPDATE_MODERATOR_SUCCESS",
  UPDATE_MODERATOR_FAILURE: "UPDATE_MODERATOR_FAILURE",

  CLEAR_ERRORS: "CLEAR_ERRORS",
};
